
espark:
  application:
    communication:
      default:
        name: "defaultService"
        enable: true
      email:
        name: "emailService"
        enable: false
      sms:
        name: "smsService"
        enable: false

