espark:
  job:
    status:
      api-configs:
        data-load:
          server-url: http://localhost:8080
          api-url: /job/status
          http-method: GET
          request-body: "{\"data\":{\"status\":[\"STARTED\",\"EXECUTING\",\"IN-QUEUE\",\"WAITING\"]}}"
          headers:
            "content-type": "application/json"